[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = [
  "cd backend && pip3 install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend && python3 manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && gunicorn tradeflow_api.wsgi --bind 0.0.0.0:${PORT:-8080}"
