# Generated by Django 5.1.5 on 2026-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TradeFlow', max_length=200)),
                ('company_tagline', models.CharField(default='Global Trade, Simplified.', max_length=300)),
                ('company_description', models.TextField(default="Expert Import-Export solutions connecting your business to the world's most lucrative markets.")),
                ('company_email', models.EmailField(default='hello@tradehub.com', max_length=254)),
                ('company_phone', models.CharField(default='+251 991 001 124', max_length=50)),
                ('company_address', models.CharField(default='123 Trade Street, New York, NY 10001', max_length=300)),
                ('hero_badge_text', models.CharField(default='TRUSTED BY 2,000+ GLOBAL ENTERPRISES', max_length=200)),
                ('hero_title', models.CharField(default='Global Trade,', max_length=200)),
                ('hero_title_highlight', models.CharField(default='Simplified.', max_length=200)),
                ('hero_subtitle', models.TextField(default="Expert Import-Export solutions connecting your business to the world's most lucrative markets.")),
                ('stat_years', models.CharField(default='15+', max_length=20)),
                ('stat_countries', models.CharField(default='50+', max_length=20)),
                ('stat_shipments', models.CharField(default='10K+', max_length=20)),
                ('about_title', models.CharField(default='Your Trusted Partner in Global Commerce', max_length=200)),
                ('about_description', models.TextField(default="For over two decades, we've been eliminating the complexity of international trade, helping businesses expand globally with confidence.")),
                ('about_story', models.TextField(default='TradeFlow was founded with a simple mission: make international trade accessible to businesses of all sizes.')),
                ('contact_email', models.EmailField(default='info@globalexports.com', max_length=254)),
                ('contact_phone', models.CharField(default='+2519 11867911', max_length=50)),
                ('contact_address', models.CharField(default='123 Trade Street, New York, NY 10001', max_length=300)),
                ('working_hours', models.CharField(default='Mon-Fri, 9 AM - 6 PM', max_length=200)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
