# Generated by Django 4.2.17 on 2026-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0004_sitesettings_about_page_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_cta_primary',
            field=models.CharField(default='Schedule Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_cta_secondary',
            field=models.CharField(default='View Services', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_cta_subtitle',
            field=models.TextField(default="Let's discuss how we can help your business expand into new markets with confidence and ease."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_cta_title',
            field=models.CharField(default='Ready to Go Global?', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_journey_subtitle',
            field=models.TextField(default='Key milestones in our growth story'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_journey_title',
            field=models.CharField(default='Our Journey', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_image',
            field=models.CharField(default='/global-trade-shipping-containers.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_values_subtitle',
            field=models.TextField(default='The principles that guide everything we do'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_values_title',
            field=models.CharField(default='Our Core Values', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature1_desc',
            field=models.TextField(default='Strategic partnerships across 150+ countries for seamless operations'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature1_title',
            field=models.CharField(default='Global Network', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature2_desc',
            field=models.TextField(default='ISO certified with full regulatory compliance in all markets'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature2_title',
            field=models.CharField(default='Compliance Expertise', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature3_desc',
            field=models.TextField(default='Scalable solutions that grow with your business needs'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature3_title',
            field=models.CharField(default='Growth Partner', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature4_desc',
            field=models.TextField(default='24/7 expert assistance from your personal trade specialists'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature4_title',
            field=models.CharField(default='Dedicated Support', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone1_desc',
            field=models.TextField(default='Started with a vision to simplify global trade'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone1_title',
            field=models.CharField(default='Company Founded', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone1_year',
            field=models.CharField(default='2004', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone2_desc',
            field=models.TextField(default='Extended services to 50+ countries'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone2_title',
            field=models.CharField(default='Global Expansion', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone2_year',
            field=models.CharField(default='2010', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone3_desc',
            field=models.TextField(default='Launched real-time tracking platform'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone3_title',
            field=models.CharField(default='Technology Integration', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone3_year',
            field=models.CharField(default='2015', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone4_desc',
            field=models.TextField(default='Recognized as top logistics provider'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone4_title',
            field=models.CharField(default='Industry Leader', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone4_year',
            field=models.CharField(default='2020', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone5_desc',
            field=models.TextField(default='Committed to eco-friendly operations'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone5_title',
            field=models.CharField(default='Sustainable Future', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='milestone5_year',
            field=models.CharField(default='2024', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value1_desc',
            field=models.TextField(default='Your success is our priority. We tailor solutions to meet your unique needs.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value1_title',
            field=models.CharField(default='Customer First', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_desc',
            field=models.TextField(default='Transparent operations and ethical practices in every transaction.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value2_title',
            field=models.CharField(default='Integrity', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_desc',
            field=models.TextField(default='Leveraging technology to streamline global trade operations.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value3_title',
            field=models.CharField(default='Innovation', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_desc',
            field=models.TextField(default='Committed to delivering exceptional service quality every time.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value4_title',
            field=models.CharField(default='Excellence', max_length=100),
        ),
    ]
