# Generated by Django 4.2.17 on 2026-03-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_staff_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
    ]
